# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('failed', 'failed'), ('pending', 'pending'), ('verified', 'verified')], default=('created', 'created'), max_length=25)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(blank=True, choices=[('kiphu', 'kiphu'), ('e_transfer', 'e_transfer'), ('cash', 'cash'), ('mercadopago', 'mercadopago'), ('webpay', 'webpay')], default=('kiphu', 'kiphu'), max_length=25)),
                ('secondary_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.OrderPlan')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('hide', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(choices=[('monthly', 'monthly'), ('quarterly', 'quarterly'), ('biannual', 'biannual'), ('annual', 'annual')], default=('annual', 'annual'), max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
        ),
        migrations.AddField(
            model_name='item',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
        ),
    ]
